/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dsg.customerorder.avro;
@org.apache.avro.specific.AvroGenerated
public enum CancelSource implements org.apache.avro.generic.GenericEnumSymbol<CancelSource> {
  CallCenter, Web, Fraud, Other  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CancelSource\",\"namespace\":\"com.dsg.customerorder.avro\",\"symbols\":[\"CallCenter\",\"Web\",\"Fraud\",\"Other\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
