/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dsg.customerorder.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Carrier {
  UPS, USPS, FEDEX, Other  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Carrier\",\"namespace\":\"com.dsg.customerorder.avro\",\"symbols\":[\"UPS\",\"USPS\",\"FEDEX\",\"Other\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
