/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dsg.customerorder.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class FulfillmentLocation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1912112074844180727L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FulfillmentLocation\",\"namespace\":\"com.dsg.customerorder.avro\",\"fields\":[{\"name\":\"shipLocationId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"fulfillmentLocationId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"fulfillmentAddress\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"FulfillmentAddress\",\"fields\":[{\"name\":\"address1\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"address2\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"address3\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"city\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"state\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"postalCode\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"country\",\"type\":[\"null\",\"string\"],\"default\":null}]}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FulfillmentLocation> ENCODER =
      new BinaryMessageEncoder<FulfillmentLocation>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FulfillmentLocation> DECODER =
      new BinaryMessageDecoder<FulfillmentLocation>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<FulfillmentLocation> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<FulfillmentLocation> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<FulfillmentLocation> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<FulfillmentLocation>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this FulfillmentLocation to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a FulfillmentLocation from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a FulfillmentLocation instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static FulfillmentLocation fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence shipLocationId;
   private java.lang.CharSequence fulfillmentLocationId;
   private com.dsg.customerorder.avro.FulfillmentAddress fulfillmentAddress;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FulfillmentLocation() {}

  /**
   * All-args constructor.
   * @param shipLocationId The new value for shipLocationId
   * @param fulfillmentLocationId The new value for fulfillmentLocationId
   * @param fulfillmentAddress The new value for fulfillmentAddress
   */
  public FulfillmentLocation(java.lang.CharSequence shipLocationId, java.lang.CharSequence fulfillmentLocationId, com.dsg.customerorder.avro.FulfillmentAddress fulfillmentAddress) {
    this.shipLocationId = shipLocationId;
    this.fulfillmentLocationId = fulfillmentLocationId;
    this.fulfillmentAddress = fulfillmentAddress;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return shipLocationId;
    case 1: return fulfillmentLocationId;
    case 2: return fulfillmentAddress;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: shipLocationId = (java.lang.CharSequence)value$; break;
    case 1: fulfillmentLocationId = (java.lang.CharSequence)value$; break;
    case 2: fulfillmentAddress = (com.dsg.customerorder.avro.FulfillmentAddress)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'shipLocationId' field.
   * @return The value of the 'shipLocationId' field.
   */
  public java.lang.CharSequence getShipLocationId() {
    return shipLocationId;
  }


  /**
   * Sets the value of the 'shipLocationId' field.
   * @param value the value to set.
   */
  public void setShipLocationId(java.lang.CharSequence value) {
    this.shipLocationId = value;
  }

  /**
   * Gets the value of the 'fulfillmentLocationId' field.
   * @return The value of the 'fulfillmentLocationId' field.
   */
  public java.lang.CharSequence getFulfillmentLocationId() {
    return fulfillmentLocationId;
  }


  /**
   * Sets the value of the 'fulfillmentLocationId' field.
   * @param value the value to set.
   */
  public void setFulfillmentLocationId(java.lang.CharSequence value) {
    this.fulfillmentLocationId = value;
  }

  /**
   * Gets the value of the 'fulfillmentAddress' field.
   * @return The value of the 'fulfillmentAddress' field.
   */
  public com.dsg.customerorder.avro.FulfillmentAddress getFulfillmentAddress() {
    return fulfillmentAddress;
  }


  /**
   * Sets the value of the 'fulfillmentAddress' field.
   * @param value the value to set.
   */
  public void setFulfillmentAddress(com.dsg.customerorder.avro.FulfillmentAddress value) {
    this.fulfillmentAddress = value;
  }

  /**
   * Creates a new FulfillmentLocation RecordBuilder.
   * @return A new FulfillmentLocation RecordBuilder
   */
  public static com.dsg.customerorder.avro.FulfillmentLocation.Builder newBuilder() {
    return new com.dsg.customerorder.avro.FulfillmentLocation.Builder();
  }

  /**
   * Creates a new FulfillmentLocation RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FulfillmentLocation RecordBuilder
   */
  public static com.dsg.customerorder.avro.FulfillmentLocation.Builder newBuilder(com.dsg.customerorder.avro.FulfillmentLocation.Builder other) {
    if (other == null) {
      return new com.dsg.customerorder.avro.FulfillmentLocation.Builder();
    } else {
      return new com.dsg.customerorder.avro.FulfillmentLocation.Builder(other);
    }
  }

  /**
   * Creates a new FulfillmentLocation RecordBuilder by copying an existing FulfillmentLocation instance.
   * @param other The existing instance to copy.
   * @return A new FulfillmentLocation RecordBuilder
   */
  public static com.dsg.customerorder.avro.FulfillmentLocation.Builder newBuilder(com.dsg.customerorder.avro.FulfillmentLocation other) {
    if (other == null) {
      return new com.dsg.customerorder.avro.FulfillmentLocation.Builder();
    } else {
      return new com.dsg.customerorder.avro.FulfillmentLocation.Builder(other);
    }
  }

  /**
   * RecordBuilder for FulfillmentLocation instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FulfillmentLocation>
    implements org.apache.avro.data.RecordBuilder<FulfillmentLocation> {

    private java.lang.CharSequence shipLocationId;
    private java.lang.CharSequence fulfillmentLocationId;
    private com.dsg.customerorder.avro.FulfillmentAddress fulfillmentAddress;
    private com.dsg.customerorder.avro.FulfillmentAddress.Builder fulfillmentAddressBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.dsg.customerorder.avro.FulfillmentLocation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.shipLocationId)) {
        this.shipLocationId = data().deepCopy(fields()[0].schema(), other.shipLocationId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.fulfillmentLocationId)) {
        this.fulfillmentLocationId = data().deepCopy(fields()[1].schema(), other.fulfillmentLocationId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.fulfillmentAddress)) {
        this.fulfillmentAddress = data().deepCopy(fields()[2].schema(), other.fulfillmentAddress);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (other.hasFulfillmentAddressBuilder()) {
        this.fulfillmentAddressBuilder = com.dsg.customerorder.avro.FulfillmentAddress.newBuilder(other.getFulfillmentAddressBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing FulfillmentLocation instance
     * @param other The existing instance to copy.
     */
    private Builder(com.dsg.customerorder.avro.FulfillmentLocation other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.shipLocationId)) {
        this.shipLocationId = data().deepCopy(fields()[0].schema(), other.shipLocationId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.fulfillmentLocationId)) {
        this.fulfillmentLocationId = data().deepCopy(fields()[1].schema(), other.fulfillmentLocationId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.fulfillmentAddress)) {
        this.fulfillmentAddress = data().deepCopy(fields()[2].schema(), other.fulfillmentAddress);
        fieldSetFlags()[2] = true;
      }
      this.fulfillmentAddressBuilder = null;
    }

    /**
      * Gets the value of the 'shipLocationId' field.
      * @return The value.
      */
    public java.lang.CharSequence getShipLocationId() {
      return shipLocationId;
    }


    /**
      * Sets the value of the 'shipLocationId' field.
      * @param value The value of 'shipLocationId'.
      * @return This builder.
      */
    public com.dsg.customerorder.avro.FulfillmentLocation.Builder setShipLocationId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.shipLocationId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'shipLocationId' field has been set.
      * @return True if the 'shipLocationId' field has been set, false otherwise.
      */
    public boolean hasShipLocationId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'shipLocationId' field.
      * @return This builder.
      */
    public com.dsg.customerorder.avro.FulfillmentLocation.Builder clearShipLocationId() {
      shipLocationId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'fulfillmentLocationId' field.
      * @return The value.
      */
    public java.lang.CharSequence getFulfillmentLocationId() {
      return fulfillmentLocationId;
    }


    /**
      * Sets the value of the 'fulfillmentLocationId' field.
      * @param value The value of 'fulfillmentLocationId'.
      * @return This builder.
      */
    public com.dsg.customerorder.avro.FulfillmentLocation.Builder setFulfillmentLocationId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.fulfillmentLocationId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'fulfillmentLocationId' field has been set.
      * @return True if the 'fulfillmentLocationId' field has been set, false otherwise.
      */
    public boolean hasFulfillmentLocationId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'fulfillmentLocationId' field.
      * @return This builder.
      */
    public com.dsg.customerorder.avro.FulfillmentLocation.Builder clearFulfillmentLocationId() {
      fulfillmentLocationId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'fulfillmentAddress' field.
      * @return The value.
      */
    public com.dsg.customerorder.avro.FulfillmentAddress getFulfillmentAddress() {
      return fulfillmentAddress;
    }


    /**
      * Sets the value of the 'fulfillmentAddress' field.
      * @param value The value of 'fulfillmentAddress'.
      * @return This builder.
      */
    public com.dsg.customerorder.avro.FulfillmentLocation.Builder setFulfillmentAddress(com.dsg.customerorder.avro.FulfillmentAddress value) {
      validate(fields()[2], value);
      this.fulfillmentAddressBuilder = null;
      this.fulfillmentAddress = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'fulfillmentAddress' field has been set.
      * @return True if the 'fulfillmentAddress' field has been set, false otherwise.
      */
    public boolean hasFulfillmentAddress() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'fulfillmentAddress' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.dsg.customerorder.avro.FulfillmentAddress.Builder getFulfillmentAddressBuilder() {
      if (fulfillmentAddressBuilder == null) {
        if (hasFulfillmentAddress()) {
          setFulfillmentAddressBuilder(com.dsg.customerorder.avro.FulfillmentAddress.newBuilder(fulfillmentAddress));
        } else {
          setFulfillmentAddressBuilder(com.dsg.customerorder.avro.FulfillmentAddress.newBuilder());
        }
      }
      return fulfillmentAddressBuilder;
    }

    /**
     * Sets the Builder instance for the 'fulfillmentAddress' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.dsg.customerorder.avro.FulfillmentLocation.Builder setFulfillmentAddressBuilder(com.dsg.customerorder.avro.FulfillmentAddress.Builder value) {
      clearFulfillmentAddress();
      fulfillmentAddressBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'fulfillmentAddress' field has an active Builder instance
     * @return True if the 'fulfillmentAddress' field has an active Builder instance
     */
    public boolean hasFulfillmentAddressBuilder() {
      return fulfillmentAddressBuilder != null;
    }

    /**
      * Clears the value of the 'fulfillmentAddress' field.
      * @return This builder.
      */
    public com.dsg.customerorder.avro.FulfillmentLocation.Builder clearFulfillmentAddress() {
      fulfillmentAddress = null;
      fulfillmentAddressBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FulfillmentLocation build() {
      try {
        FulfillmentLocation record = new FulfillmentLocation();
        record.shipLocationId = fieldSetFlags()[0] ? this.shipLocationId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.fulfillmentLocationId = fieldSetFlags()[1] ? this.fulfillmentLocationId : (java.lang.CharSequence) defaultValue(fields()[1]);
        if (fulfillmentAddressBuilder != null) {
          try {
            record.fulfillmentAddress = this.fulfillmentAddressBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("fulfillmentAddress"));
            throw e;
          }
        } else {
          record.fulfillmentAddress = fieldSetFlags()[2] ? this.fulfillmentAddress : (com.dsg.customerorder.avro.FulfillmentAddress) defaultValue(fields()[2]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FulfillmentLocation>
    WRITER$ = (org.apache.avro.io.DatumWriter<FulfillmentLocation>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FulfillmentLocation>
    READER$ = (org.apache.avro.io.DatumReader<FulfillmentLocation>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.shipLocationId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.shipLocationId);
    }

    if (this.fulfillmentLocationId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.fulfillmentLocationId);
    }

    if (this.fulfillmentAddress == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.fulfillmentAddress.customEncode(out);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.shipLocationId = null;
      } else {
        this.shipLocationId = in.readString(this.shipLocationId instanceof Utf8 ? (Utf8)this.shipLocationId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.fulfillmentLocationId = null;
      } else {
        this.fulfillmentLocationId = in.readString(this.fulfillmentLocationId instanceof Utf8 ? (Utf8)this.fulfillmentLocationId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.fulfillmentAddress = null;
      } else {
        if (this.fulfillmentAddress == null) {
          this.fulfillmentAddress = new com.dsg.customerorder.avro.FulfillmentAddress();
        }
        this.fulfillmentAddress.customDecode(in);
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.shipLocationId = null;
          } else {
            this.shipLocationId = in.readString(this.shipLocationId instanceof Utf8 ? (Utf8)this.shipLocationId : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.fulfillmentLocationId = null;
          } else {
            this.fulfillmentLocationId = in.readString(this.fulfillmentLocationId instanceof Utf8 ? (Utf8)this.fulfillmentLocationId : null);
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.fulfillmentAddress = null;
          } else {
            if (this.fulfillmentAddress == null) {
              this.fulfillmentAddress = new com.dsg.customerorder.avro.FulfillmentAddress();
            }
            this.fulfillmentAddress.customDecode(in);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










