/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dsg.customerorder.avro;
@org.apache.avro.specific.AvroGenerated
public enum OrderType implements org.apache.avro.generic.GenericEnumSymbol<OrderType> {
  ReshipNoReturn, ReshipReturnRequired, None, BOPIS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrderType\",\"namespace\":\"com.dsg.customerorder.avro\",\"symbols\":[\"ReshipNoReturn\",\"ReshipReturnRequired\",\"None\",\"BOPIS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
