/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dsg.customerorder.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ReturnDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5226824334946715400L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ReturnDetails\",\"namespace\":\"com.dsg.customerorder.avro\",\"fields\":[{\"name\":\"returnTrackingId\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ReturnDetails> ENCODER =
      new BinaryMessageEncoder<ReturnDetails>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ReturnDetails> DECODER =
      new BinaryMessageDecoder<ReturnDetails>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ReturnDetails> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ReturnDetails> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ReturnDetails>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ReturnDetails to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ReturnDetails from a ByteBuffer. */
  public static ReturnDetails fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence returnTrackingId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ReturnDetails() {}

  /**
   * All-args constructor.
   * @param returnTrackingId The new value for returnTrackingId
   */
  public ReturnDetails(java.lang.CharSequence returnTrackingId) {
    this.returnTrackingId = returnTrackingId;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return returnTrackingId;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: returnTrackingId = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'returnTrackingId' field.
   * @return The value of the 'returnTrackingId' field.
   */
  public java.lang.CharSequence getReturnTrackingId() {
    return returnTrackingId;
  }

  /**
   * Sets the value of the 'returnTrackingId' field.
   * @param value the value to set.
   */
  public void setReturnTrackingId(java.lang.CharSequence value) {
    this.returnTrackingId = value;
  }

  /**
   * Creates a new ReturnDetails RecordBuilder.
   * @return A new ReturnDetails RecordBuilder
   */
  public static com.dsg.customerorder.avro.ReturnDetails.Builder newBuilder() {
    return new com.dsg.customerorder.avro.ReturnDetails.Builder();
  }

  /**
   * Creates a new ReturnDetails RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ReturnDetails RecordBuilder
   */
  public static com.dsg.customerorder.avro.ReturnDetails.Builder newBuilder(com.dsg.customerorder.avro.ReturnDetails.Builder other) {
    return new com.dsg.customerorder.avro.ReturnDetails.Builder(other);
  }

  /**
   * Creates a new ReturnDetails RecordBuilder by copying an existing ReturnDetails instance.
   * @param other The existing instance to copy.
   * @return A new ReturnDetails RecordBuilder
   */
  public static com.dsg.customerorder.avro.ReturnDetails.Builder newBuilder(com.dsg.customerorder.avro.ReturnDetails other) {
    return new com.dsg.customerorder.avro.ReturnDetails.Builder(other);
  }

  /**
   * RecordBuilder for ReturnDetails instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ReturnDetails>
    implements org.apache.avro.data.RecordBuilder<ReturnDetails> {

    private java.lang.CharSequence returnTrackingId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.dsg.customerorder.avro.ReturnDetails.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.returnTrackingId)) {
        this.returnTrackingId = data().deepCopy(fields()[0].schema(), other.returnTrackingId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ReturnDetails instance
     * @param other The existing instance to copy.
     */
    private Builder(com.dsg.customerorder.avro.ReturnDetails other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.returnTrackingId)) {
        this.returnTrackingId = data().deepCopy(fields()[0].schema(), other.returnTrackingId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'returnTrackingId' field.
      * @return The value.
      */
    public java.lang.CharSequence getReturnTrackingId() {
      return returnTrackingId;
    }

    /**
      * Sets the value of the 'returnTrackingId' field.
      * @param value The value of 'returnTrackingId'.
      * @return This builder.
      */
    public com.dsg.customerorder.avro.ReturnDetails.Builder setReturnTrackingId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.returnTrackingId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'returnTrackingId' field has been set.
      * @return True if the 'returnTrackingId' field has been set, false otherwise.
      */
    public boolean hasReturnTrackingId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'returnTrackingId' field.
      * @return This builder.
      */
    public com.dsg.customerorder.avro.ReturnDetails.Builder clearReturnTrackingId() {
      returnTrackingId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ReturnDetails build() {
      try {
        ReturnDetails record = new ReturnDetails();
        record.returnTrackingId = fieldSetFlags()[0] ? this.returnTrackingId : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ReturnDetails>
    WRITER$ = (org.apache.avro.io.DatumWriter<ReturnDetails>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ReturnDetails>
    READER$ = (org.apache.avro.io.DatumReader<ReturnDetails>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
