/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.dsg.customerorder.avro;
@org.apache.avro.specific.AvroGenerated
public enum State implements org.apache.avro.generic.GenericEnumSymbol<State> {
  placed, in_review, canceled, ready_to_fulfill, in_fulfillment, fulfilled  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"State\",\"namespace\":\"com.dsg.customerorder.avro\",\"symbols\":[\"placed\",\"in_review\",\"canceled\",\"ready_to_fulfill\",\"in_fulfillment\",\"fulfilled\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
